# Site settings
title: Cevi Herdian
email: itsmecevi@gmail.com
description: Cevi Herdian - Data-Driven Strategist
baseurl:  # the subpath of your site, e.g. /blog/
url: itsmecevi.github.io
# twitter_username: twitter_username
# github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"
redirects: yes

collections:
  portfolio:
    output: true
    permalink: /projects/:path/

theme: jekyll-theme-minimal
